# Generated by Django 5.0.7 on 2024-08-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_category_alter_event_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
